"""SpectralBrain statistics -- analysis, EDA/QC, Bayesian, normative, surrogates, clustering.

- :mod:`.analysis` -- vertex-wise inference, effect sizes, classification,
  dimension collapsing, RSA/Mantel, network metrics, asymmetry, embeddings,
  exploratory QC (spectral QC, optimal k, ICC, batch effects) and the
  descriptor recommendation engine.
- :mod:`.bayesian` -- Bayesian models and their MCMC samplers.
- :mod:`.normative` -- harmonisation and normative modelling.
- :mod:`.surrogates` -- bootstrap, null models, synthetic generators.
- :mod:`.clustering` -- clustering and partition statistics (subpackage).
"""

from spectralbrain.statistics import clustering  # noqa: F401
from spectralbrain.statistics.analysis import (  # noqa: F401
    ClassificationResult,
    DescriptorRecommendation,
    OptimalKResult,
    SpectralQCReport,
    VertexWiseResult,
    asymmetry_test,
    bag_of_spectral_words,
    batch_effect_scan,
    classify,
    cohens_d_map,
    compute_icc,
    descriptor_correlation,
    descriptor_profile,
    eigenvalue_stability,
    emd_distance,
    energy_distance,
    fisher_vector,
    fit_gmm_codebook,
    hedges_g_map,
    intra_inter_ratio,
    js_divergence,
    kernel_mean_embedding,
    kl_divergence,
    lateralisation_index,
    mantel_test,
    modularity,
    optimal_k,
    participation_coefficient,
    rdm,
    recommend_descriptor,
    rsa_compare,
    spectral_mds,
    spectral_pca,
    spectral_qc,
    spectral_umap,
    surprise_map,
    surprise_map_percentile,
    tfce,
    vertexwise_correlation,
    vertexwise_mannwhitney,
    vertexwise_permutation,
    vertexwise_ttest,
)
from spectralbrain.statistics.bayesian import (  # noqa: F401
    BayesianConnectome,
    BayesianGroupComparison,
    BayesianModel,
    BayesianSpatialModel,
    BlackjaxSampler,
    GaussianProcessNormative,
    HierarchicalLinearModel,
    HorseshoeRegression,
    NumPyroSampler,
    NutpieSampler,
    PyMCSampler,
    SamplerConfig,
    get_bayesian_sampler,
    get_gpu_bayesian_sampler,
)
from spectralbrain.statistics.clustering import (  # noqa: F401
    BayesianClusterConfirmation,
    ClusterResult,
    DDCRPTuningResult,
    FusionResult,
    MapperResult,
    ScaleSpaceBlobResult,
    TemporalClusterResult,
    TensorDecompositionResult,
    VineyardResult,
    adjusted_rand_index,
    aggregate_across_subjects,
    auto_cluster,
    autotune_ddcrp,
    build_descriptor_distance,
    build_hks_affinity_graph,
    build_hybrid_distance,
    cluster_atlas_concordance,
    cluster_comparison,
    cluster_consensus,
    cluster_ddcrp,
    cluster_ddcrp_functional,
    cluster_dpmm,
    cluster_gnmf,
    cluster_hdbscan,
    cluster_joint_spectral,
    cluster_leiden,
    cluster_mapper,
    cluster_multiview,
    cluster_persistence,
    cluster_quality,
    cluster_scalespace_blobs,
    cluster_spatiotemporal_gnmf,
    cluster_spatiotemporal_stdbscan,
    cluster_spectral_coclustering,
    cluster_temporal_dtw,
    cluster_temporal_fpca,
    cluster_tensor_decomposition,
    cluster_vineyards,
    cluster_wavelet_coefficients,
    compare_partitions,
    confirm_clusters_bayesian,
    denoise_joint_timevertex,
    fuse_concatenate,
    fuse_joint_nmf,
    fuse_multi_kernel,
    homogeneity_vs_null,
    normalized_mutual_info,
    parcel_overlap,
    random_parcellation,
    spatial_rand_index,
    spectral_homogeneity,
    variation_of_information,
)
from spectralbrain.statistics.normative import (  # noqa: F401
    HarmonizationResult,
    MethodComparisonResult,
    NonInferiorityResult,
    NormativeModel,
    auc_comparison_delong,
    centile_curves,
    combat_apply,
    compare_methods,
    equivalence_test_tost,
    extreme_value_map,
    harmonize,
    harmonize_combat,
    harmonize_combat_gam,
    non_inferiority_test,
    z_score_map,
)
from spectralbrain.statistics.surrogates import (  # noqa: F401
    SyntheticDescriptors,
    SyntheticMesh,
    bootstrap_ci,
    bootstrap_paired_difference,
    null_brainsmash,
    null_edge_rewiring,
    null_eigenstrapping,
    null_eigenvalue_permutation,
    null_parametric,
    null_phase_randomisation,
    null_spin_permutation,
    null_subject_permutation,
)
